[ids]
*

[main]
capslock=overload(control, esc)
insert=S-insert
leftshift+leftmeta+f23 = rightcontrol
altgr=overload(altgr, macro(space M-2))
menu=macro(esc M-2)

[shift]
leftshift=capslock
rightshift=capslock
